/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'david' at '10/28/15 5:15 PM' with Gradle 2.6
 *
 * @author david, @date 10/28/15 5:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
